// This file was generated by counterfeiter
package fake_evacuation_context

import (
	"sync"

	"github.com/cloudfoundry-incubator/rep/evacuation/evacuation_context"
)

type FakeEvacuationReporter struct {
	EvacuatingStub        func() bool
	evacuatingMutex       sync.RWMutex
	evacuatingArgsForCall []struct{}
	evacuatingReturns struct {
		result1 bool
	}
}

func (fake *FakeEvacuationReporter) Evacuating() bool {
	fake.evacuatingMutex.Lock()
	fake.evacuatingArgsForCall = append(fake.evacuatingArgsForCall, struct{}{})
	fake.evacuatingMutex.Unlock()
	if fake.EvacuatingStub != nil {
		return fake.EvacuatingStub()
	} else {
		return fake.evacuatingReturns.result1
	}
}

func (fake *FakeEvacuationReporter) EvacuatingCallCount() int {
	fake.evacuatingMutex.RLock()
	defer fake.evacuatingMutex.RUnlock()
	return len(fake.evacuatingArgsForCall)
}

func (fake *FakeEvacuationReporter) EvacuatingReturns(result1 bool) {
	fake.EvacuatingStub = nil
	fake.evacuatingReturns = struct {
		result1 bool
	}{result1}
}

var _ evacuation_context.EvacuationReporter = new(FakeEvacuationReporter)
