// This file was generated by counterfeiter
package fake_evacuation_context

import (
	"sync"

	"code.cloudfoundry.org/rep/evacuation/evacuation_context"
)

type FakeEvacuatable struct {
	EvacuateStub        func()
	evacuateMutex       sync.RWMutex
	evacuateArgsForCall []struct{}
}

func (fake *FakeEvacuatable) Evacuate() {
	fake.evacuateMutex.Lock()
	fake.evacuateArgsForCall = append(fake.evacuateArgsForCall, struct{}{})
	fake.evacuateMutex.Unlock()
	if fake.EvacuateStub != nil {
		fake.EvacuateStub()
	}
}

func (fake *FakeEvacuatable) EvacuateCallCount() int {
	fake.evacuateMutex.RLock()
	defer fake.evacuateMutex.RUnlock()
	return len(fake.evacuateArgsForCall)
}

var _ evacuation_context.Evacuatable = new(FakeEvacuatable)
