// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/executor"
	"github.com/cloudfoundry-incubator/rep/tallyman"
)

type FakeProcessor struct {
	ProcessStub        func(executor.Container)
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		arg1 executor.Container
	}
}

func (fake *FakeProcessor) Process(arg1 executor.Container) {
	fake.processMutex.Lock()
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		arg1 executor.Container
	}{arg1})
	fake.processMutex.Unlock()
	if fake.ProcessStub != nil {
		fake.ProcessStub(arg1)
	}
}

func (fake *FakeProcessor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *FakeProcessor) ProcessArgsForCall(i int) executor.Container {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return fake.processArgsForCall[i].arg1
}

var _ tallyman.Processor = new(FakeProcessor)
