// This file was generated by counterfeiter
package fake_lrp_stopper

import (
	"sync"

	"github.com/cloudfoundry-incubator/rep/lrp_stopper"
)

type FakeLRPStopper struct {
	StopInstanceStub        func(processGuid, instanceGuid string) error
	stopInstanceMutex       sync.RWMutex
	stopInstanceArgsForCall []struct {
		processGuid  string
		instanceGuid string
	}
	stopInstanceReturns struct {
		result1 error
	}
}

func (fake *FakeLRPStopper) StopInstance(processGuid string, instanceGuid string) error {
	fake.stopInstanceMutex.Lock()
	fake.stopInstanceArgsForCall = append(fake.stopInstanceArgsForCall, struct {
		processGuid  string
		instanceGuid string
	}{processGuid, instanceGuid})
	fake.stopInstanceMutex.Unlock()
	if fake.StopInstanceStub != nil {
		return fake.StopInstanceStub(processGuid, instanceGuid)
	} else {
		return fake.stopInstanceReturns.result1
	}
}

func (fake *FakeLRPStopper) StopInstanceCallCount() int {
	fake.stopInstanceMutex.RLock()
	defer fake.stopInstanceMutex.RUnlock()
	return len(fake.stopInstanceArgsForCall)
}

func (fake *FakeLRPStopper) StopInstanceArgsForCall(i int) (string, string) {
	fake.stopInstanceMutex.RLock()
	defer fake.stopInstanceMutex.RUnlock()
	return fake.stopInstanceArgsForCall[i].processGuid, fake.stopInstanceArgsForCall[i].instanceGuid
}

func (fake *FakeLRPStopper) StopInstanceReturns(result1 error) {
	fake.StopInstanceStub = nil
	fake.stopInstanceReturns = struct {
		result1 error
	}{result1}
}

var _ lrp_stopper.LRPStopper = new(FakeLRPStopper)
