// This file was generated by counterfeiter
package fake_snapshot

import (
	"sync"

	"github.com/cloudfoundry-incubator/rep/snapshot"
)

type FakeSnapshot struct {
	GuidStub        func() string
	guidMutex       sync.RWMutex
	guidArgsForCall []struct{}
	guidReturns struct {
		result1 string
	}
}

func (fake *FakeSnapshot) Guid() string {
	fake.guidMutex.Lock()
	fake.guidArgsForCall = append(fake.guidArgsForCall, struct{}{})
	fake.guidMutex.Unlock()
	if fake.GuidStub != nil {
		return fake.GuidStub()
	} else {
		return fake.guidReturns.result1
	}
}

func (fake *FakeSnapshot) GuidCallCount() int {
	fake.guidMutex.RLock()
	defer fake.guidMutex.RUnlock()
	return len(fake.guidArgsForCall)
}

func (fake *FakeSnapshot) GuidReturns(result1 string) {
	fake.GuidStub = nil
	fake.guidReturns = struct {
		result1 string
	}{result1}
}

var _ snapshot.Snapshot = new(FakeSnapshot)
