// This file was generated by counterfeiter
package fake_snapshot

import (
	"sync"

	"github.com/cloudfoundry-incubator/rep/snapshot"
	"github.com/pivotal-golang/lager"
)

type FakeLRPProcessor struct {
	ProcessStub        func(lager.Logger, *snapshot.LRPSnapshot)
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		arg1 lager.Logger
		arg2 *snapshot.LRPSnapshot
	}
}

func (fake *FakeLRPProcessor) Process(arg1 lager.Logger, arg2 *snapshot.LRPSnapshot) {
	fake.processMutex.Lock()
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		arg1 lager.Logger
		arg2 *snapshot.LRPSnapshot
	}{arg1, arg2})
	fake.processMutex.Unlock()
	if fake.ProcessStub != nil {
		fake.ProcessStub(arg1, arg2)
	}
}

func (fake *FakeLRPProcessor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *FakeLRPProcessor) ProcessArgsForCall(i int) (lager.Logger, *snapshot.LRPSnapshot) {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return fake.processArgsForCall[i].arg1, fake.processArgsForCall[i].arg2
}

var _ snapshot.LRPProcessor = new(FakeLRPProcessor)
