// This file was generated by counterfeiter
package fake_gatherer

import (
	"sync"

	"github.com/cloudfoundry-incubator/rep/gatherer"
)

type FakeProcessor struct {
	ProcessStub        func(snapshot gatherer.Snapshot)
	processMutex       sync.RWMutex
	processArgsForCall []struct {
		snapshot gatherer.Snapshot
	}
}

func (fake *FakeProcessor) Process(snapshot gatherer.Snapshot) {
	fake.processMutex.Lock()
	fake.processArgsForCall = append(fake.processArgsForCall, struct {
		snapshot gatherer.Snapshot
	}{snapshot})
	fake.processMutex.Unlock()
	if fake.ProcessStub != nil {
		fake.ProcessStub(snapshot)
	}
}

func (fake *FakeProcessor) ProcessCallCount() int {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return len(fake.processArgsForCall)
}

func (fake *FakeProcessor) ProcessArgsForCall(i int) gatherer.Snapshot {
	fake.processMutex.RLock()
	defer fake.processMutex.RUnlock()
	return fake.processArgsForCall[i].snapshot
}

var _ gatherer.Processor = new(FakeProcessor)
