// This file was generated by counterfeiter
package fake_bbs

import (
	"github.com/cloudfoundry-incubator/runtime-schema/bbs"

	"github.com/cloudfoundry-incubator/runtime-schema/models"

	"sync"
)

type FakeMetricsBBS struct {
	GetAllTasksStub        func() ([]models.Task, error)
	getAllTasksMutex       sync.RWMutex
	getAllTasksArgsForCall []struct{}
	getAllTasksReturns     struct {
		result1 []models.Task
		result2 error
	}
	GetServiceRegistrationsStub        func() (models.ServiceRegistrations, error)
	getServiceRegistrationsMutex       sync.RWMutex
	getServiceRegistrationsArgsForCall []struct{}
	getServiceRegistrationsReturns     struct {
		result1 models.ServiceRegistrations
		result2 error
	}
	GetAllFreshnessStub        func() ([]string, error)
	getAllFreshnessMutex       sync.RWMutex
	getAllFreshnessArgsForCall []struct{}
	getAllFreshnessReturns     struct {
		result1 []string
		result2 error
	}
}

func (fake *FakeMetricsBBS) GetAllTasks() ([]models.Task, error) {
	fake.getAllTasksMutex.Lock()
	defer fake.getAllTasksMutex.Unlock()
	fake.getAllTasksArgsForCall = append(fake.getAllTasksArgsForCall, struct{}{})
	if fake.GetAllTasksStub != nil {
		return fake.GetAllTasksStub()
	} else {
		return fake.getAllTasksReturns.result1, fake.getAllTasksReturns.result2
	}
}

func (fake *FakeMetricsBBS) GetAllTasksCallCount() int {
	fake.getAllTasksMutex.RLock()
	defer fake.getAllTasksMutex.RUnlock()
	return len(fake.getAllTasksArgsForCall)
}

func (fake *FakeMetricsBBS) GetAllTasksReturns(result1 []models.Task, result2 error) {
	fake.getAllTasksReturns = struct {
		result1 []models.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricsBBS) GetServiceRegistrations() (models.ServiceRegistrations, error) {
	fake.getServiceRegistrationsMutex.Lock()
	defer fake.getServiceRegistrationsMutex.Unlock()
	fake.getServiceRegistrationsArgsForCall = append(fake.getServiceRegistrationsArgsForCall, struct{}{})
	if fake.GetServiceRegistrationsStub != nil {
		return fake.GetServiceRegistrationsStub()
	} else {
		return fake.getServiceRegistrationsReturns.result1, fake.getServiceRegistrationsReturns.result2
	}
}

func (fake *FakeMetricsBBS) GetServiceRegistrationsCallCount() int {
	fake.getServiceRegistrationsMutex.RLock()
	defer fake.getServiceRegistrationsMutex.RUnlock()
	return len(fake.getServiceRegistrationsArgsForCall)
}

func (fake *FakeMetricsBBS) GetServiceRegistrationsReturns(result1 models.ServiceRegistrations, result2 error) {
	fake.getServiceRegistrationsReturns = struct {
		result1 models.ServiceRegistrations
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricsBBS) GetAllFreshness() ([]string, error) {
	fake.getAllFreshnessMutex.Lock()
	defer fake.getAllFreshnessMutex.Unlock()
	fake.getAllFreshnessArgsForCall = append(fake.getAllFreshnessArgsForCall, struct{}{})
	if fake.GetAllFreshnessStub != nil {
		return fake.GetAllFreshnessStub()
	} else {
		return fake.getAllFreshnessReturns.result1, fake.getAllFreshnessReturns.result2
	}
}

func (fake *FakeMetricsBBS) GetAllFreshnessCallCount() int {
	fake.getAllFreshnessMutex.RLock()
	defer fake.getAllFreshnessMutex.RUnlock()
	return len(fake.getAllFreshnessArgsForCall)
}

func (fake *FakeMetricsBBS) GetAllFreshnessReturns(result1 []string, result2 error) {
	fake.getAllFreshnessReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

var _ bbs.MetricsBBS = new(FakeMetricsBBS)
