// Code generated by counterfeiter. DO NOT EDIT.
package handlersfakes

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"code.cloudfoundry.org/rep"
	"code.cloudfoundry.org/rep/handlers"
)

type FakeMetricCollector struct {
	MetricsStub        func(logger lager.Logger) (*rep.ContainerMetricsCollection, error)
	metricsMutex       sync.RWMutex
	metricsArgsForCall []struct {
		logger lager.Logger
	}
	metricsReturns struct {
		result1 *rep.ContainerMetricsCollection
		result2 error
	}
	metricsReturnsOnCall map[int]struct {
		result1 *rep.ContainerMetricsCollection
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetricCollector) Metrics(logger lager.Logger) (*rep.ContainerMetricsCollection, error) {
	fake.metricsMutex.Lock()
	ret, specificReturn := fake.metricsReturnsOnCall[len(fake.metricsArgsForCall)]
	fake.metricsArgsForCall = append(fake.metricsArgsForCall, struct {
		logger lager.Logger
	}{logger})
	fake.recordInvocation("Metrics", []interface{}{logger})
	fake.metricsMutex.Unlock()
	if fake.MetricsStub != nil {
		return fake.MetricsStub(logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.metricsReturns.result1, fake.metricsReturns.result2
}

func (fake *FakeMetricCollector) MetricsCallCount() int {
	fake.metricsMutex.RLock()
	defer fake.metricsMutex.RUnlock()
	return len(fake.metricsArgsForCall)
}

func (fake *FakeMetricCollector) MetricsArgsForCall(i int) lager.Logger {
	fake.metricsMutex.RLock()
	defer fake.metricsMutex.RUnlock()
	return fake.metricsArgsForCall[i].logger
}

func (fake *FakeMetricCollector) MetricsReturns(result1 *rep.ContainerMetricsCollection, result2 error) {
	fake.MetricsStub = nil
	fake.metricsReturns = struct {
		result1 *rep.ContainerMetricsCollection
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricCollector) MetricsReturnsOnCall(i int, result1 *rep.ContainerMetricsCollection, result2 error) {
	fake.MetricsStub = nil
	if fake.metricsReturnsOnCall == nil {
		fake.metricsReturnsOnCall = make(map[int]struct {
			result1 *rep.ContainerMetricsCollection
			result2 error
		})
	}
	fake.metricsReturnsOnCall[i] = struct {
		result1 *rep.ContainerMetricsCollection
		result2 error
	}{result1, result2}
}

func (fake *FakeMetricCollector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.metricsMutex.RLock()
	defer fake.metricsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetricCollector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.MetricCollector = new(FakeMetricCollector)
